function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -20; // Pirate
	global.__objectDepths[1] = 0; // PiratePreview
	global.__objectDepths[2] = 10; // Ship
	global.__objectDepths[3] = -10; // ShipSlot
	global.__objectDepths[4] = -15; // Cargo
	global.__objectDepths[5] = -1000; // NotifacationList
	global.__objectDepths[6] = -1000; // DumpItem
	global.__objectDepths[7] = 0; // ConquerPannel
	global.__objectDepths[8] = 25; // Clock
	global.__objectDepths[9] = 0; // Cloud
	global.__objectDepths[10] = 0; // WeatherController
	global.__objectDepths[11] = -10; // EnemyAttack
	global.__objectDepths[12] = -100; // UseFoodAnimation
	global.__objectDepths[13] = 0; // SpeechController
	global.__objectDepths[14] = 0; // SoundController
	global.__objectDepths[15] = -100; // PirateLeveler
	global.__objectDepths[16] = 0; // MoraleDisplay
	global.__objectDepths[17] = 0; // ViewController
	global.__objectDepths[18] = 0; // GameStatsController
	global.__objectDepths[19] = 0; // Defeat
	global.__objectDepths[20] = -1000; // MapShip
	global.__objectDepths[21] = -1000; // LandingSpot
	global.__objectDepths[22] = 8; // MapCreator
	global.__objectDepths[23] = -11; // Island
	global.__objectDepths[24] = -12; // MapMarker
	global.__objectDepths[25] = 0; // PortDrawerBack
	global.__objectDepths[26] = 0; // PortDrawerFront
	global.__objectDepths[27] = 0; // DrawPort
	global.__objectDepths[28] = 10; // Tavern
	global.__objectDepths[29] = 10; // Smithy
	global.__objectDepths[30] = 10; // Tailors
	global.__objectDepths[31] = 10; // ShipYard
	global.__objectDepths[32] = 10; // TrinketShop
	global.__objectDepths[33] = 0; // LandFlavor
	global.__objectDepths[34] = 10; // Camp
	global.__objectDepths[35] = 0; // Sleeping
	global.__objectDepths[36] = 5; // Bat
	global.__objectDepths[37] = 15; // JungleBird
	global.__objectDepths[38] = 0; // TreasureChest
	global.__objectDepths[39] = 0; // RopeHook
	global.__objectDepths[40] = 5; // OasisSplash
	global.__objectDepths[41] = 10; // BarrelCargo
	global.__objectDepths[42] = 10; // ChestCargo
	global.__objectDepths[43] = 10; // ChestItem
	global.__objectDepths[44] = -15; // Event
	global.__objectDepths[45] = -15; // Request
	global.__objectDepths[46] = 0; // EventController
	global.__objectDepths[47] = 0; // ConditionTimer
	global.__objectDepths[48] = 0; // FoodTimer
	global.__objectDepths[49] = 5; // EventDrawer
	global.__objectDepths[50] = 0; // ShipEvent
	global.__objectDepths[51] = 5; // Dolphins
	global.__objectDepths[52] = 5; // Barrel
	global.__objectDepths[53] = 5; // GiantTurtleDrawer
	global.__objectDepths[54] = 0; // RaftEvent
	global.__objectDepths[55] = 0; // TradingPostEvent
	global.__objectDepths[56] = 0; // MermaidEvent
	global.__objectDepths[57] = 0; // BirdEvent
	global.__objectDepths[58] = 0; // FishEvent
	global.__objectDepths[59] = 0; // CharacterParent
	global.__objectDepths[60] = 0; // CharacterCreator
	global.__objectDepths[61] = 0; // JohnnyShortsticks
	global.__objectDepths[62] = 0; // CoveCollector
	global.__objectDepths[63] = 0; // CaptainSilverwheel
	global.__objectDepths[64] = 0; // FrogKing
	global.__objectDepths[65] = 0; // GiantTurtle
	global.__objectDepths[66] = 0; // ObjectVarsRunner
	global.__objectDepths[67] = -1000; // ItemParent
	global.__objectDepths[68] = -100000; // ItemRunner
	global.__objectDepths[69] = -9; // Store
	global.__objectDepths[70] = -1000; // StoreAreYouSure
	global.__objectDepths[71] = 0; // StoreObjectParent
	global.__objectDepths[72] = -25; // StoreObjectItem
	global.__objectDepths[73] = -25; // StoreObjectStorable
	global.__objectDepths[74] = -25; // StoreObjectTrade
	global.__objectDepths[75] = -25; // StoreObjectHealth
	global.__objectDepths[76] = -25; // StoreObjectVictory
	global.__objectDepths[77] = -25; // StoreObjectShip
	global.__objectDepths[78] = -25; // StoreObjectPirate
	global.__objectDepths[79] = -8; // CombatRunner
	global.__objectDepths[80] = 0; // DamageController
	global.__objectDepths[81] = -1000; // SurrenderOption
	global.__objectDepths[82] = -8; // Enemy
	global.__objectDepths[83] = -10; // EnemyShip
	global.__objectDepths[84] = -10; // EnemyCollectors
	global.__objectDepths[85] = -10; // SilverwheelEnemy
	global.__objectDepths[86] = 0; // EnemyCollector
	global.__objectDepths[87] = 0; // EnemySilverwheel
	global.__objectDepths[88] = 0; // EnemyPirate
	global.__objectDepths[89] = 0; // EnemyCaptain
	global.__objectDepths[90] = 0; // EnemyAdmiral
	global.__objectDepths[91] = 0; // EnemyCannonier
	global.__objectDepths[92] = -10; // Merchant
	global.__objectDepths[93] = 0; // MerchantCrew
	global.__objectDepths[94] = 0; // ShipGaurd
	global.__objectDepths[95] = 0; // MerchantCaptain
	global.__objectDepths[96] = -10; // TropicalEnemy
	global.__objectDepths[97] = -10; // TropicalEnemySword
	global.__objectDepths[98] = -10; // TropicalEnemyRoyal
	global.__objectDepths[99] = 0; // EnemyFrogCrew
	global.__objectDepths[100] = 0; // EnemyFrogGunner
	global.__objectDepths[101] = 0; // EnemyFrogCannon
	global.__objectDepths[102] = 0; // EnemyRoyalFrogCrew
	global.__objectDepths[103] = 0; // EnemyRoyalFrogCannon
	global.__objectDepths[104] = 0; // EnemyFrogCaptain
	global.__objectDepths[105] = -20; // PlayerActionRunner
	global.__objectDepths[106] = -8; // ActionParent
	global.__objectDepths[107] = 0; // LostEyeAction
	global.__objectDepths[108] = 0; // BlankAction
	global.__objectDepths[109] = 0; // BasicMeleeAction
	global.__objectDepths[110] = 0; // HeavyBoardingAction
	global.__objectDepths[111] = 0; // SwarmAction
	global.__objectDepths[112] = 0; // HammerBlowAction
	global.__objectDepths[113] = 0; // ScoutingAction
	global.__objectDepths[114] = 0; // FinishingStabAction
	global.__objectDepths[115] = 0; // HoldFastAction
	global.__objectDepths[116] = 0; // MonkeyBiteAction
	global.__objectDepths[117] = 0; // BasicRangedAction
	global.__objectDepths[118] = 0; // BarrageAction
	global.__objectDepths[119] = 0; // LookoutAction
	global.__objectDepths[120] = 0; // TargetedFireAction
	global.__objectDepths[121] = 0; // SniperAction
	global.__objectDepths[122] = 0; // CauseChaosAction
	global.__objectDepths[123] = 0; // BleedingShotAction
	global.__objectDepths[124] = 0; // ParrotSquawkAction
	global.__objectDepths[125] = 0; // BasicCannonAction
	global.__objectDepths[126] = 0; // BroadsideAction
	global.__objectDepths[127] = 0; // WarningShotAction
	global.__objectDepths[128] = 0; // CannonSprayAction
	global.__objectDepths[129] = 0; // ChainShotAction
	global.__objectDepths[130] = 0; // ShrapnelAction
	global.__objectDepths[131] = 0; // ConcentratedFireAction
	global.__objectDepths[132] = 0; // MonkeyCannonAction
	global.__objectDepths[133] = 0; // BasicShipAction
	global.__objectDepths[134] = 0; // BasicRunAction
	global.__objectDepths[135] = 0; // OutmaneuverAction
	global.__objectDepths[136] = 0; // SurgeryAction
	global.__objectDepths[137] = 0; // RammingAction
	global.__objectDepths[138] = 0; // EngageAction
	global.__objectDepths[139] = 0; // DisengageAction
	global.__objectDepths[140] = 0; // SurpriseAction
	global.__objectDepths[141] = -50; // RealAttack
	global.__objectDepths[142] = -50; // ShipAttack
	global.__objectDepths[143] = -15; // AttackAnimation
	global.__objectDepths[144] = -50; // ShipSwordAttack
	global.__objectDepths[145] = -50; // ShipHeavyBoardingAttack
	global.__objectDepths[146] = -50; // ShipSwarmAttack
	global.__objectDepths[147] = -50; // ShipHammerAttack
	global.__objectDepths[148] = -50; // ShipScoutAttack
	global.__objectDepths[149] = -50; // ShipFinishingAttack
	global.__objectDepths[150] = -50; // ShipHoldFastAttack
	global.__objectDepths[151] = -50; // MonkeyBiteAttack
	global.__objectDepths[152] = -50; // ShipGunAttack
	global.__objectDepths[153] = -50; // ShipBarrageAttack
	global.__objectDepths[154] = -50; // ShipLookoutAttack
	global.__objectDepths[155] = -50; // ShipChaosAttack
	global.__objectDepths[156] = -50; // ShipSniperAttack
	global.__objectDepths[157] = -50; // ShipTargetedAttack
	global.__objectDepths[158] = -50; // BleedingShotAttack
	global.__objectDepths[159] = -50; // ParrotSquawkAttack
	global.__objectDepths[160] = -50; // ShipCannonAttack
	global.__objectDepths[161] = -50; // BroadsideAttack
	global.__objectDepths[162] = -50; // ShipWarningAttack
	global.__objectDepths[163] = -50; // SprayAttack
	global.__objectDepths[164] = -50; // ChainShotAttack
	global.__objectDepths[165] = -50; // ShrapnelAttack
	global.__objectDepths[166] = -50; // ConcentratedFireAttack
	global.__objectDepths[167] = -50; // MonkeyCannonAttack
	global.__objectDepths[168] = -50; // ShipShipChange
	global.__objectDepths[169] = -50; // ShipShipRun
	global.__objectDepths[170] = -50; // ShipEngageAttack
	global.__objectDepths[171] = -50; // ShipDisengageAttack
	global.__objectDepths[172] = -50; // ShipOutmaneuver
	global.__objectDepths[173] = -50; // ShipSurgery
	global.__objectDepths[174] = -50; // ShipRamming
	global.__objectDepths[175] = -50; // ShipSurpriseAttack
	global.__objectDepths[176] = 0; // EffectParent
	global.__objectDepths[177] = -8; // OldCombatRunner
	global.__objectDepths[178] = -10001; // LoadingScreenWaves
	global.__objectDepths[179] = 0; // SaveGameRunner
	global.__objectDepths[180] = -10; // TitleObject
	global.__objectDepths[181] = 0; // MenuButtonMaker
	global.__objectDepths[182] = 10; // MainMenuBackgroundRunner
	global.__objectDepths[183] = 0; // MenuButton
	global.__objectDepths[184] = 0; // NewGameMaker
	global.__objectDepths[185] = 0; // LoadGameMaker
	global.__objectDepths[186] = 0; // MenuCloud
	global.__objectDepths[187] = 10; // ChoosePirateBackgroundRunner
	global.__objectDepths[188] = -10000; // ChoosePirateParent
	global.__objectDepths[189] = -10000; // ChooseCaptain
	global.__objectDepths[190] = -10000; // ChooseFirstMate
	global.__objectDepths[191] = 0; // ChoosePirateShip
	global.__objectDepths[192] = 0; // LightParent
	global.__objectDepths[193] = 0; // TestLight
	global.__objectDepths[194] = 0; // SunLight
	global.__objectDepths[195] = 0; // MoonLight


	global.__objectNames[0] = "Pirate";
	global.__objectNames[1] = "PiratePreview";
	global.__objectNames[2] = "Ship";
	global.__objectNames[3] = "ShipSlot";
	global.__objectNames[4] = "Cargo";
	global.__objectNames[5] = "NotifacationList";
	global.__objectNames[6] = "DumpItem";
	global.__objectNames[7] = "ConquerPannel";
	global.__objectNames[8] = "Clock";
	global.__objectNames[9] = "Cloud";
	global.__objectNames[10] = "WeatherController";
	global.__objectNames[11] = "EnemyAttack";
	global.__objectNames[12] = "UseFoodAnimation";
	global.__objectNames[13] = "SpeechController";
	global.__objectNames[14] = "SoundController";
	global.__objectNames[15] = "PirateLeveler";
	global.__objectNames[16] = "MoraleDisplay";
	global.__objectNames[17] = "ViewController";
	global.__objectNames[18] = "GameStatsController";
	global.__objectNames[19] = "Defeat";
	global.__objectNames[20] = "MapShip";
	global.__objectNames[21] = "LandingSpot";
	global.__objectNames[22] = "MapCreator";
	global.__objectNames[23] = "Island";
	global.__objectNames[24] = "MapMarker";
	global.__objectNames[25] = "PortDrawerBack";
	global.__objectNames[26] = "PortDrawerFront";
	global.__objectNames[27] = "DrawPort";
	global.__objectNames[28] = "Tavern";
	global.__objectNames[29] = "Smithy";
	global.__objectNames[30] = "Tailors";
	global.__objectNames[31] = "ShipYard";
	global.__objectNames[32] = "TrinketShop";
	global.__objectNames[33] = "LandFlavor";
	global.__objectNames[34] = "Camp";
	global.__objectNames[35] = "Sleeping";
	global.__objectNames[36] = "Bat";
	global.__objectNames[37] = "JungleBird";
	global.__objectNames[38] = "TreasureChest";
	global.__objectNames[39] = "RopeHook";
	global.__objectNames[40] = "OasisSplash";
	global.__objectNames[41] = "BarrelCargo";
	global.__objectNames[42] = "ChestCargo";
	global.__objectNames[43] = "ChestItem";
	global.__objectNames[44] = "Event";
	global.__objectNames[45] = "Request";
	global.__objectNames[46] = "EventController";
	global.__objectNames[47] = "ConditionTimer";
	global.__objectNames[48] = "FoodTimer";
	global.__objectNames[49] = "EventDrawer";
	global.__objectNames[50] = "ShipEvent";
	global.__objectNames[51] = "Dolphins";
	global.__objectNames[52] = "Barrel";
	global.__objectNames[53] = "GiantTurtleDrawer";
	global.__objectNames[54] = "RaftEvent";
	global.__objectNames[55] = "TradingPostEvent";
	global.__objectNames[56] = "MermaidEvent";
	global.__objectNames[57] = "BirdEvent";
	global.__objectNames[58] = "FishEvent";
	global.__objectNames[59] = "CharacterParent";
	global.__objectNames[60] = "CharacterCreator";
	global.__objectNames[61] = "JohnnyShortsticks";
	global.__objectNames[62] = "CoveCollector";
	global.__objectNames[63] = "CaptainSilverwheel";
	global.__objectNames[64] = "FrogKing";
	global.__objectNames[65] = "GiantTurtle";
	global.__objectNames[66] = "ObjectVarsRunner";
	global.__objectNames[67] = "ItemParent";
	global.__objectNames[68] = "ItemRunner";
	global.__objectNames[69] = "Store";
	global.__objectNames[70] = "StoreAreYouSure";
	global.__objectNames[71] = "StoreObjectParent";
	global.__objectNames[72] = "StoreObjectItem";
	global.__objectNames[73] = "StoreObjectStorable";
	global.__objectNames[74] = "StoreObjectTrade";
	global.__objectNames[75] = "StoreObjectHealth";
	global.__objectNames[76] = "StoreObjectVictory";
	global.__objectNames[77] = "StoreObjectShip";
	global.__objectNames[78] = "StoreObjectPirate";
	global.__objectNames[79] = "CombatRunner";
	global.__objectNames[80] = "DamageController";
	global.__objectNames[81] = "SurrenderOption";
	global.__objectNames[82] = "Enemy";
	global.__objectNames[83] = "EnemyShip";
	global.__objectNames[84] = "EnemyCollectors";
	global.__objectNames[85] = "SilverwheelEnemy";
	global.__objectNames[86] = "EnemyCollector";
	global.__objectNames[87] = "EnemySilverwheel";
	global.__objectNames[88] = "EnemyPirate";
	global.__objectNames[89] = "EnemyCaptain";
	global.__objectNames[90] = "EnemyAdmiral";
	global.__objectNames[91] = "EnemyCannonier";
	global.__objectNames[92] = "Merchant";
	global.__objectNames[93] = "MerchantCrew";
	global.__objectNames[94] = "ShipGaurd";
	global.__objectNames[95] = "MerchantCaptain";
	global.__objectNames[96] = "TropicalEnemy";
	global.__objectNames[97] = "TropicalEnemySword";
	global.__objectNames[98] = "TropicalEnemyRoyal";
	global.__objectNames[99] = "EnemyFrogCrew";
	global.__objectNames[100] = "EnemyFrogGunner";
	global.__objectNames[101] = "EnemyFrogCannon";
	global.__objectNames[102] = "EnemyRoyalFrogCrew";
	global.__objectNames[103] = "EnemyRoyalFrogCannon";
	global.__objectNames[104] = "EnemyFrogCaptain";
	global.__objectNames[105] = "PlayerActionRunner";
	global.__objectNames[106] = "ActionParent";
	global.__objectNames[107] = "LostEyeAction";
	global.__objectNames[108] = "BlankAction";
	global.__objectNames[109] = "BasicMeleeAction";
	global.__objectNames[110] = "HeavyBoardingAction";
	global.__objectNames[111] = "SwarmAction";
	global.__objectNames[112] = "HammerBlowAction";
	global.__objectNames[113] = "ScoutingAction";
	global.__objectNames[114] = "FinishingStabAction";
	global.__objectNames[115] = "HoldFastAction";
	global.__objectNames[116] = "MonkeyBiteAction";
	global.__objectNames[117] = "BasicRangedAction";
	global.__objectNames[118] = "BarrageAction";
	global.__objectNames[119] = "LookoutAction";
	global.__objectNames[120] = "TargetedFireAction";
	global.__objectNames[121] = "SniperAction";
	global.__objectNames[122] = "CauseChaosAction";
	global.__objectNames[123] = "BleedingShotAction";
	global.__objectNames[124] = "ParrotSquawkAction";
	global.__objectNames[125] = "BasicCannonAction";
	global.__objectNames[126] = "BroadsideAction";
	global.__objectNames[127] = "WarningShotAction";
	global.__objectNames[128] = "CannonSprayAction";
	global.__objectNames[129] = "ChainShotAction";
	global.__objectNames[130] = "ShrapnelAction";
	global.__objectNames[131] = "ConcentratedFireAction";
	global.__objectNames[132] = "MonkeyCannonAction";
	global.__objectNames[133] = "BasicShipAction";
	global.__objectNames[134] = "BasicRunAction";
	global.__objectNames[135] = "OutmaneuverAction";
	global.__objectNames[136] = "SurgeryAction";
	global.__objectNames[137] = "RammingAction";
	global.__objectNames[138] = "EngageAction";
	global.__objectNames[139] = "DisengageAction";
	global.__objectNames[140] = "SurpriseAction";
	global.__objectNames[141] = "RealAttack";
	global.__objectNames[142] = "ShipAttack";
	global.__objectNames[143] = "AttackAnimation";
	global.__objectNames[144] = "ShipSwordAttack";
	global.__objectNames[145] = "ShipHeavyBoardingAttack";
	global.__objectNames[146] = "ShipSwarmAttack";
	global.__objectNames[147] = "ShipHammerAttack";
	global.__objectNames[148] = "ShipScoutAttack";
	global.__objectNames[149] = "ShipFinishingAttack";
	global.__objectNames[150] = "ShipHoldFastAttack";
	global.__objectNames[151] = "MonkeyBiteAttack";
	global.__objectNames[152] = "ShipGunAttack";
	global.__objectNames[153] = "ShipBarrageAttack";
	global.__objectNames[154] = "ShipLookoutAttack";
	global.__objectNames[155] = "ShipChaosAttack";
	global.__objectNames[156] = "ShipSniperAttack";
	global.__objectNames[157] = "ShipTargetedAttack";
	global.__objectNames[158] = "BleedingShotAttack";
	global.__objectNames[159] = "ParrotSquawkAttack";
	global.__objectNames[160] = "ShipCannonAttack";
	global.__objectNames[161] = "BroadsideAttack";
	global.__objectNames[162] = "ShipWarningAttack";
	global.__objectNames[163] = "SprayAttack";
	global.__objectNames[164] = "ChainShotAttack";
	global.__objectNames[165] = "ShrapnelAttack";
	global.__objectNames[166] = "ConcentratedFireAttack";
	global.__objectNames[167] = "MonkeyCannonAttack";
	global.__objectNames[168] = "ShipShipChange";
	global.__objectNames[169] = "ShipShipRun";
	global.__objectNames[170] = "ShipEngageAttack";
	global.__objectNames[171] = "ShipDisengageAttack";
	global.__objectNames[172] = "ShipOutmaneuver";
	global.__objectNames[173] = "ShipSurgery";
	global.__objectNames[174] = "ShipRamming";
	global.__objectNames[175] = "ShipSurpriseAttack";
	global.__objectNames[176] = "EffectParent";
	global.__objectNames[177] = "OldCombatRunner";
	global.__objectNames[178] = "LoadingScreenWaves";
	global.__objectNames[179] = "SaveGameRunner";
	global.__objectNames[180] = "TitleObject";
	global.__objectNames[181] = "MenuButtonMaker";
	global.__objectNames[182] = "MainMenuBackgroundRunner";
	global.__objectNames[183] = "MenuButton";
	global.__objectNames[184] = "NewGameMaker";
	global.__objectNames[185] = "LoadGameMaker";
	global.__objectNames[186] = "MenuCloud";
	global.__objectNames[187] = "ChoosePirateBackgroundRunner";
	global.__objectNames[188] = "ChoosePirateParent";
	global.__objectNames[189] = "ChooseCaptain";
	global.__objectNames[190] = "ChooseFirstMate";
	global.__objectNames[191] = "ChoosePirateShip";
	global.__objectNames[192] = "LightParent";
	global.__objectNames[193] = "TestLight";
	global.__objectNames[194] = "SunLight";
	global.__objectNames[195] = "MoonLight";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
