function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -10000; // CharacterCreator
	global.__objectDepths[1] = 2; // CharacterController
	global.__objectDepths[2] = 0; // CharacterCollider
	global.__objectDepths[3] = 0; // CharacterLeg
	global.__objectDepths[4] = -1; // CharacterArm
	global.__objectDepths[5] = 0; // CharacterHead
	global.__objectDepths[6] = 0; // CharacterBody
	global.__objectDepths[7] = 0; // CharacterFoot
	global.__objectDepths[8] = -1; // CharacterHand
	global.__objectDepths[9] = 0; // CloudController
	global.__objectDepths[10] = 0; // PhysicsController
	global.__objectDepths[11] = 0; // PartyPackObject
	global.__objectDepths[12] = 0; // ExitButton
	global.__objectDepths[13] = 0; // PartyButton
	global.__objectDepths[14] = 0; // GameModes
	global.__objectDepths[15] = 0; // Stands
	global.__objectDepths[16] = 0; // SoundController
	global.__objectDepths[17] = 0; // ViewController
	global.__objectDepths[18] = 0; // Ground
	global.__objectDepths[19] = 0; // DodgeBallPersistentCreator
	global.__objectDepths[20] = -1; // StageList
	global.__objectDepths[21] = 0; // Begin
	global.__objectDepths[22] = 1; // StageButton
	global.__objectDepths[23] = 0; // GamemodeButton
	global.__objectDepths[24] = 0; // StockButton
	global.__objectDepths[25] = 0; // BallAmountButton
	global.__objectDepths[26] = 1; // BallButton
	global.__objectDepths[27] = 0; // MainMenu
	global.__objectDepths[28] = 0; // ArenaLanding1
	global.__objectDepths[29] = 0; // ArenaLandingMain
	global.__objectDepths[30] = -1; // ArenaCurveLeft
	global.__objectDepths[31] = 0; // ArenaCurveRight
	global.__objectDepths[32] = 0; // ArenaLanding1Spawner
	global.__objectDepths[33] = 0; // ArenaCurveLeftSpawner
	global.__objectDepths[34] = 0; // ArenaCurveRightSpawner
	global.__objectDepths[35] = 0; // ArenaLandingMainSpawner
	global.__objectDepths[36] = 0; // FarmRailing
	global.__objectDepths[37] = 0; // FarmGround
	global.__objectDepths[38] = 0; // FarmLeftRoof
	global.__objectDepths[39] = 0; // FarmTurbine
	global.__objectDepths[40] = 0; // FarmRightRoof
	global.__objectDepths[41] = 0; // FarmTopRoof
	global.__objectDepths[42] = 0; // FarmTreeTop
	global.__objectDepths[43] = 0; // FarmTreeBranch
	global.__objectDepths[44] = 10; // FarmHouseSpawner
	global.__objectDepths[45] = 10; // FarmTreeSpawner
	global.__objectDepths[46] = 0; // FarmGroundSpawner
	global.__objectDepths[47] = 0; // BlimpTop
	global.__objectDepths[48] = -5; // BlimpPlatform1
	global.__objectDepths[49] = -5; // BlimpPlatform2
	global.__objectDepths[50] = -1; // BlimpPlatform3
	global.__objectDepths[51] = -5; // BlimpBasket
	global.__objectDepths[52] = 5; // BlimpSpawner
	global.__objectDepths[53] = 5; // BoatSpawner
	global.__objectDepths[54] = -1; // BoatTop
	global.__objectDepths[55] = -1; // BoatUpper
	global.__objectDepths[56] = -5; // BoatLeft
	global.__objectDepths[57] = -5; // BoatRight
	global.__objectDepths[58] = -5; // BoatFloor
	global.__objectDepths[59] = -6; // BoatWheel
	global.__objectDepths[60] = 0; // BoatSpoke
	global.__objectDepths[61] = 100; // Cloud
	global.__objectDepths[62] = 5; // FerrisWheelSpawner
	global.__objectDepths[63] = -16; // FerrisWheelStand
	global.__objectDepths[64] = -1; // FerrisWheelLower
	global.__objectDepths[65] = -1; // FerrisWheelSpoke
	global.__objectDepths[66] = -5; // FerrisWheelCar
	global.__objectDepths[67] = -5; // FerrisWheelLeftWall
	global.__objectDepths[68] = -5; // FerrisWheelRightWall
	global.__objectDepths[69] = -15; // FerrisWheelCircle
	global.__objectDepths[70] = 5; // FerrisWheelRoofSpawner
	global.__objectDepths[71] = -20; // FerrisWheelRoof
	global.__objectDepths[72] = 5; // FerrisWheeGameSpawner
	global.__objectDepths[73] = -1; // FerrisWheelGame
	global.__objectDepths[74] = -1; // FerrisWheelGameTop
	global.__objectDepths[75] = -5; // BridgeBridge
	global.__objectDepths[76] = 0; // BridgeCar
	global.__objectDepths[77] = -5; // BridgeGroundLeft
	global.__objectDepths[78] = -5; // BridgeGroundRight
	global.__objectDepths[79] = -5; // BridgeLowerLeft
	global.__objectDepths[80] = -5; // BridgeLowerRight
	global.__objectDepths[81] = -1; // BridgeSpawner
	global.__objectDepths[82] = -5; // BridgeUpperLeft
	global.__objectDepths[83] = -5; // BridgeUpperRight
	global.__objectDepths[84] = 0; // CannonBall
	global.__objectDepths[85] = -5; // CastleBottom
	global.__objectDepths[86] = 0; // CastleCreator
	global.__objectDepths[87] = -5; // CastleGround
	global.__objectDepths[88] = -5; // CastleLeft
	global.__objectDepths[89] = -5; // CastleRight
	global.__objectDepths[90] = 5; // CastleSpawner
	global.__objectDepths[91] = -5; // CastleTop
	global.__objectDepths[92] = 5; // FactorySpawner
	global.__objectDepths[93] = -1; // FactoryRoof
	global.__objectDepths[94] = -1; // FactoryLower
	global.__objectDepths[95] = -1; // FactoryLowerBelt
	global.__objectDepths[96] = -1; // FactoryPipe
	global.__objectDepths[97] = 5; // FactoryGroundSpawner
	global.__objectDepths[98] = -10; // FactoryGround
	global.__objectDepths[99] = 4; // FactoryWheel
	global.__objectDepths[100] = -2; // FactoryPoint
	global.__objectDepths[101] = 0; // FactoryBelt
	global.__objectDepths[102] = 10; // FactoryCloud
	global.__objectDepths[103] = -1; // FactoryCar
	global.__objectDepths[104] = 5; // SkiLodgeSpawner
	global.__objectDepths[105] = -10; // SkiLodgeGround
	global.__objectDepths[106] = -1; // SkiLodgeLeftRoof
	global.__objectDepths[107] = -1; // SkiLodgeRightRoof
	global.__objectDepths[108] = -1; // SkiLodgeLongRoof
	global.__objectDepths[109] = -1; // SkiLodgeRightRail
	global.__objectDepths[110] = -1; // SkiLodgeLeftRail
	global.__objectDepths[111] = 0; // SkiLiftSpawner
	global.__objectDepths[112] = -2; // SkiLiftPoint
	global.__objectDepths[113] = -1; // SkiLiftChair
	global.__objectDepths[114] = 0; // DodgeBallTimer
	global.__objectDepths[115] = 0; // ExplotionParticle
	global.__objectDepths[116] = 0; // WaterParticle
	global.__objectDepths[117] = 0; // ContactParticle
	global.__objectDepths[118] = 0; // Bomb
	global.__objectDepths[119] = 0; // SoccerBall
	global.__objectDepths[120] = 0; // WaterBalloonBall
	global.__objectDepths[121] = 0; // EggBall
	global.__objectDepths[122] = 0; // DodgeBall
	global.__objectDepths[123] = 0; // BowlingBall
	global.__objectDepths[124] = 0; // SuperBall
	global.__objectDepths[125] = 0; // StickyBall
	global.__objectDepths[126] = 0; // RocketBall
	global.__objectDepths[127] = 0; // FootBall
	global.__objectDepths[128] = 0; // Balloon
	global.__objectDepths[129] = 0; // Chicken
	global.__objectDepths[130] = 0; // ChickenWing
	global.__objectDepths[131] = 0; // DodgeBallParent
	global.__objectDepths[132] = 0; // GolfGamemodeButton
	global.__objectDepths[133] = 0; // GolfTimeOut
	global.__objectDepths[134] = 0; // BeginGolf
	global.__objectDepths[135] = -15; // GolfGrass0
	global.__objectDepths[136] = -15; // GolfGrass1
	global.__objectDepths[137] = -15; // GolfGrass2
	global.__objectDepths[138] = -15; // GolfGrass3
	global.__objectDepths[139] = -15; // GolfGrass4
	global.__objectDepths[140] = -15; // GolfGrass5
	global.__objectDepths[141] = 0; // GrassDrawer
	global.__objectDepths[142] = -14; // GrassOutliner
	global.__objectDepths[143] = 0; // LavaDrop
	global.__objectDepths[144] = 0; // GreenParent
	global.__objectDepths[145] = 0; // Green0
	global.__objectDepths[146] = 0; // Green1
	global.__objectDepths[147] = 0; // SandParent
	global.__objectDepths[148] = -10; // GolfSand0
	global.__objectDepths[149] = -10; // GolfSand1
	global.__objectDepths[150] = -5; // GolfWater
	global.__objectDepths[151] = 0; // Rock
	global.__objectDepths[152] = 0; // TreeParent
	global.__objectDepths[153] = 0; // PineTreeSpawner
	global.__objectDepths[154] = 0; // PineTreeTrunk
	global.__objectDepths[155] = 0; // PineTreeBranchesBottom
	global.__objectDepths[156] = 0; // PineTreeBranchesMid
	global.__objectDepths[157] = 0; // PineTreeBranchesTop
	global.__objectDepths[158] = 0; // SmallTreeSpawner
	global.__objectDepths[159] = 0; // SmallTreeTrunk
	global.__objectDepths[160] = 0; // SmallTreeLeftBranch
	global.__objectDepths[161] = 0; // SmallTreeRightBranch
	global.__objectDepths[162] = 0; // SmallTreeTopBranch
	global.__objectDepths[163] = -5; // GolfTurbine
	global.__objectDepths[164] = -5; // GolfTurbineBack
	global.__objectDepths[165] = 1; // GolfWindmill
	global.__objectDepths[166] = 10; // GolfWindmillSpawner
	global.__objectDepths[167] = 0; // GolfClub
	global.__objectDepths[168] = 0; // TeeBox
	global.__objectDepths[169] = 0; // GolfBall
	global.__objectDepths[170] = 0; // GolfBallGhost
	global.__objectDepths[171] = -11; // BallMarker
	global.__objectDepths[172] = 0; // GolfFlagSpawner
	global.__objectDepths[173] = 0; // GolfFlag
	global.__objectDepths[174] = 0; // GolfFlagFlag
	global.__objectDepths[175] = 0; // LastHole


	global.__objectNames[0] = "CharacterCreator";
	global.__objectNames[1] = "CharacterController";
	global.__objectNames[2] = "CharacterCollider";
	global.__objectNames[3] = "CharacterLeg";
	global.__objectNames[4] = "CharacterArm";
	global.__objectNames[5] = "CharacterHead";
	global.__objectNames[6] = "CharacterBody";
	global.__objectNames[7] = "CharacterFoot";
	global.__objectNames[8] = "CharacterHand";
	global.__objectNames[9] = "CloudController";
	global.__objectNames[10] = "PhysicsController";
	global.__objectNames[11] = "PartyPackObject";
	global.__objectNames[12] = "ExitButton";
	global.__objectNames[13] = "PartyButton";
	global.__objectNames[14] = "GameModes";
	global.__objectNames[15] = "Stands";
	global.__objectNames[16] = "SoundController";
	global.__objectNames[17] = "ViewController";
	global.__objectNames[18] = "Ground";
	global.__objectNames[19] = "DodgeBallPersistentCreator";
	global.__objectNames[20] = "StageList";
	global.__objectNames[21] = "Begin";
	global.__objectNames[22] = "StageButton";
	global.__objectNames[23] = "GamemodeButton";
	global.__objectNames[24] = "StockButton";
	global.__objectNames[25] = "BallAmountButton";
	global.__objectNames[26] = "BallButton";
	global.__objectNames[27] = "MainMenu";
	global.__objectNames[28] = "ArenaLanding1";
	global.__objectNames[29] = "ArenaLandingMain";
	global.__objectNames[30] = "ArenaCurveLeft";
	global.__objectNames[31] = "ArenaCurveRight";
	global.__objectNames[32] = "ArenaLanding1Spawner";
	global.__objectNames[33] = "ArenaCurveLeftSpawner";
	global.__objectNames[34] = "ArenaCurveRightSpawner";
	global.__objectNames[35] = "ArenaLandingMainSpawner";
	global.__objectNames[36] = "FarmRailing";
	global.__objectNames[37] = "FarmGround";
	global.__objectNames[38] = "FarmLeftRoof";
	global.__objectNames[39] = "FarmTurbine";
	global.__objectNames[40] = "FarmRightRoof";
	global.__objectNames[41] = "FarmTopRoof";
	global.__objectNames[42] = "FarmTreeTop";
	global.__objectNames[43] = "FarmTreeBranch";
	global.__objectNames[44] = "FarmHouseSpawner";
	global.__objectNames[45] = "FarmTreeSpawner";
	global.__objectNames[46] = "FarmGroundSpawner";
	global.__objectNames[47] = "BlimpTop";
	global.__objectNames[48] = "BlimpPlatform1";
	global.__objectNames[49] = "BlimpPlatform2";
	global.__objectNames[50] = "BlimpPlatform3";
	global.__objectNames[51] = "BlimpBasket";
	global.__objectNames[52] = "BlimpSpawner";
	global.__objectNames[53] = "BoatSpawner";
	global.__objectNames[54] = "BoatTop";
	global.__objectNames[55] = "BoatUpper";
	global.__objectNames[56] = "BoatLeft";
	global.__objectNames[57] = "BoatRight";
	global.__objectNames[58] = "BoatFloor";
	global.__objectNames[59] = "BoatWheel";
	global.__objectNames[60] = "BoatSpoke";
	global.__objectNames[61] = "Cloud";
	global.__objectNames[62] = "FerrisWheelSpawner";
	global.__objectNames[63] = "FerrisWheelStand";
	global.__objectNames[64] = "FerrisWheelLower";
	global.__objectNames[65] = "FerrisWheelSpoke";
	global.__objectNames[66] = "FerrisWheelCar";
	global.__objectNames[67] = "FerrisWheelLeftWall";
	global.__objectNames[68] = "FerrisWheelRightWall";
	global.__objectNames[69] = "FerrisWheelCircle";
	global.__objectNames[70] = "FerrisWheelRoofSpawner";
	global.__objectNames[71] = "FerrisWheelRoof";
	global.__objectNames[72] = "FerrisWheeGameSpawner";
	global.__objectNames[73] = "FerrisWheelGame";
	global.__objectNames[74] = "FerrisWheelGameTop";
	global.__objectNames[75] = "BridgeBridge";
	global.__objectNames[76] = "BridgeCar";
	global.__objectNames[77] = "BridgeGroundLeft";
	global.__objectNames[78] = "BridgeGroundRight";
	global.__objectNames[79] = "BridgeLowerLeft";
	global.__objectNames[80] = "BridgeLowerRight";
	global.__objectNames[81] = "BridgeSpawner";
	global.__objectNames[82] = "BridgeUpperLeft";
	global.__objectNames[83] = "BridgeUpperRight";
	global.__objectNames[84] = "CannonBall";
	global.__objectNames[85] = "CastleBottom";
	global.__objectNames[86] = "CastleCreator";
	global.__objectNames[87] = "CastleGround";
	global.__objectNames[88] = "CastleLeft";
	global.__objectNames[89] = "CastleRight";
	global.__objectNames[90] = "CastleSpawner";
	global.__objectNames[91] = "CastleTop";
	global.__objectNames[92] = "FactorySpawner";
	global.__objectNames[93] = "FactoryRoof";
	global.__objectNames[94] = "FactoryLower";
	global.__objectNames[95] = "FactoryLowerBelt";
	global.__objectNames[96] = "FactoryPipe";
	global.__objectNames[97] = "FactoryGroundSpawner";
	global.__objectNames[98] = "FactoryGround";
	global.__objectNames[99] = "FactoryWheel";
	global.__objectNames[100] = "FactoryPoint";
	global.__objectNames[101] = "FactoryBelt";
	global.__objectNames[102] = "FactoryCloud";
	global.__objectNames[103] = "FactoryCar";
	global.__objectNames[104] = "SkiLodgeSpawner";
	global.__objectNames[105] = "SkiLodgeGround";
	global.__objectNames[106] = "SkiLodgeLeftRoof";
	global.__objectNames[107] = "SkiLodgeRightRoof";
	global.__objectNames[108] = "SkiLodgeLongRoof";
	global.__objectNames[109] = "SkiLodgeRightRail";
	global.__objectNames[110] = "SkiLodgeLeftRail";
	global.__objectNames[111] = "SkiLiftSpawner";
	global.__objectNames[112] = "SkiLiftPoint";
	global.__objectNames[113] = "SkiLiftChair";
	global.__objectNames[114] = "DodgeBallTimer";
	global.__objectNames[115] = "ExplotionParticle";
	global.__objectNames[116] = "WaterParticle";
	global.__objectNames[117] = "ContactParticle";
	global.__objectNames[118] = "Bomb";
	global.__objectNames[119] = "SoccerBall";
	global.__objectNames[120] = "WaterBalloonBall";
	global.__objectNames[121] = "EggBall";
	global.__objectNames[122] = "DodgeBall";
	global.__objectNames[123] = "BowlingBall";
	global.__objectNames[124] = "SuperBall";
	global.__objectNames[125] = "StickyBall";
	global.__objectNames[126] = "RocketBall";
	global.__objectNames[127] = "FootBall";
	global.__objectNames[128] = "Balloon";
	global.__objectNames[129] = "Chicken";
	global.__objectNames[130] = "ChickenWing";
	global.__objectNames[131] = "DodgeBallParent";
	global.__objectNames[132] = "GolfGamemodeButton";
	global.__objectNames[133] = "GolfTimeOut";
	global.__objectNames[134] = "BeginGolf";
	global.__objectNames[135] = "GolfGrass0";
	global.__objectNames[136] = "GolfGrass1";
	global.__objectNames[137] = "GolfGrass2";
	global.__objectNames[138] = "GolfGrass3";
	global.__objectNames[139] = "GolfGrass4";
	global.__objectNames[140] = "GolfGrass5";
	global.__objectNames[141] = "GrassDrawer";
	global.__objectNames[142] = "GrassOutliner";
	global.__objectNames[143] = "LavaDrop";
	global.__objectNames[144] = "GreenParent";
	global.__objectNames[145] = "Green0";
	global.__objectNames[146] = "Green1";
	global.__objectNames[147] = "SandParent";
	global.__objectNames[148] = "GolfSand0";
	global.__objectNames[149] = "GolfSand1";
	global.__objectNames[150] = "GolfWater";
	global.__objectNames[151] = "Rock";
	global.__objectNames[152] = "TreeParent";
	global.__objectNames[153] = "PineTreeSpawner";
	global.__objectNames[154] = "PineTreeTrunk";
	global.__objectNames[155] = "PineTreeBranchesBottom";
	global.__objectNames[156] = "PineTreeBranchesMid";
	global.__objectNames[157] = "PineTreeBranchesTop";
	global.__objectNames[158] = "SmallTreeSpawner";
	global.__objectNames[159] = "SmallTreeTrunk";
	global.__objectNames[160] = "SmallTreeLeftBranch";
	global.__objectNames[161] = "SmallTreeRightBranch";
	global.__objectNames[162] = "SmallTreeTopBranch";
	global.__objectNames[163] = "GolfTurbine";
	global.__objectNames[164] = "GolfTurbineBack";
	global.__objectNames[165] = "GolfWindmill";
	global.__objectNames[166] = "GolfWindmillSpawner";
	global.__objectNames[167] = "GolfClub";
	global.__objectNames[168] = "TeeBox";
	global.__objectNames[169] = "GolfBall";
	global.__objectNames[170] = "GolfBallGhost";
	global.__objectNames[171] = "BallMarker";
	global.__objectNames[172] = "GolfFlagSpawner";
	global.__objectNames[173] = "GolfFlag";
	global.__objectNames[174] = "GolfFlagFlag";
	global.__objectNames[175] = "LastHole";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
