/// @description Speech Dicts

pirateDict0 = ds_map_create()
pirateDict1 = ds_map_create()

pirateDict0[? " am "] = " be "
pirateDict0[? " your "] = " yer "
pirateDict0[? " are "] = " be "
pirateDict0[? " you're "] = " yer "
pirateDict0[? " yes "] = " Aye "
pirateDict0[? " my "] = " me "
pirateDict0[? " i'm "] = " i be "
pirateDict0[? " that's "] = " that be "
pirateDict0[? " it's "] = " it be "
pirateDict0[? " he's "] = " he be "
pirateDict0[? " she's "] = " she be "
pirateDict0[? " who's "] = " who be "
pirateDict0[? " where's "] = " where be "
pirateDict0[? " when's "] = " when be "
pirateDict0[? " why's "] = " why be "
pirateDict0[? " how's "] = " why be "
pirateDict0[? " is "] = " be "

pirateDict1[? " hello "] = " ahoy "
pirateDict1[? " became "] = " now be "
pirateDict1[? " will "] = " shall be "
pirateDict1[? " left "] = " port "
pirateDict1[? " right "] = " starboard "
pirateDict1[? " treasure "] = " booty "
pirateDict1[? " gold "] = " pieces "
pirateDict1[? " captain "] = " capt'n "
pirateDict1[? "ing "] = "in' "
pirateDict1[? " and "] = " an' "
pirateDict1[? " the "] = " th' "
pirateDict1[? " of "] = " o' "
pirateDict1[? " enemy "] = " scallywags "
pirateDict1[? " h"] = " '"
pirateDict1[? " was "] = " been "
pirateDict1[? " there "] = " thar "
pirateDict1[? " e"] = " '"
pirateDict1[? " hungry "] = " starvin' "
pirateDict1[? " ship "] = " sea bucket "
pirateDict1[? " ocean "] = " sea "
pirateDict1[? " ocean "] = " briney deep "
pirateDict1[? " sea "] = " briney deep "
pirateDict1[? " i "] = " me "
pirateDict1[? " okay "] = " savvy "
pirateDict1[? " damage "] = " wounds "
pirateDict1[? " drowned "] = " sleeping with the fishes"
pirateDict1[? " drown "] = "sleep with the fishes "
pirateDict1[? " dead "] = " in Davey Jones locker "
pirateDict1[? " die "] = " head to Davey Jones locker "
pirateDict1[? " crew "] = " hearties "
pirateDict1[? " sunk "] = " scuttled "
pirateDict1[? " back "] = " aft "
pirateDict1[? " gold "] = " booty "
pirateDict1[? " you'll "] = " yer "
pirateDict1[? " food "] = " grub "
pirateDict1[? " boards "] = " planks "
pirateDict1[? " meal "] = " grub "
pirateDict1[? " drink "] = " swish "
pirateDict1[? " wind "] = " gusts "
pirateDict1[? " meself "] = " meself "
pirateDict1[? " can "] = " may "
pirateDict1[? " had "] = " be havin' "




