/// @description BackStory

backStart[0] = "Hello there captain! "
backStart[1] = "Hello! "
backStart[2] = "Arr there friend! "
backStart[3] = "Captain! "
backStart[4] = ""
backStart[5] = "Excuse me. "
backStart[6] = "Hello there! "
backStart[7] = "Over here! "

backMiddle[0] = "I'm looking for a good ship to crew! "
backMiddle[1] = "I'd like to explore the ocean! "
backMiddle[2] = "Need an extra pair of hands? "  
backMiddle[3] = "Looking for more crew? "
backMiddle[4] = "Want me on board your ship? "
backMiddle[5] = "I want to get rich beyond belief! " 
backMiddle[7] = "You look to be in need of a good pirate. "
backMiddle[8] = "Your ship needs more crew. "
backMiddle[9] = "I'm looking to plunder the 7 seas! "
backMiddle[10] = "I want to find some treasure! "
backMiddle[11] = "I am looking for a good crew to join! "
backMiddle[12] = ""
backMiddle[13] = "I'd like to taunt the hangman's noose. "

backSecond[0] = "I also need some gold. "
backSecond[1] = "I can hear the sea calling me! "
backSecond[3] = "Please! "
backSecond[4] = ""
backSecond[5] = "You've got plenty of gold. "
backSecond[6] = "I won't drink too much of your grog. "
backSecond[7] = "I've always wanted to explore the world! "
backSecond[8] = "I'm not getting any younger. "
backSecond[9] = "I hear there's lots of gold to find!"
backSecond[10] = "I need a change in my life. "
backSecond[11] = "I'd like to find what's out there! "
backSecond[12] = "I'm not asking too much. "

backEnd[0] = "Will you let me on board?"
backEnd[1] = "What do you say?"
backEnd[2] = ""
backEnd[3] = "You won't regret having me aboard!"
backEnd[4] = "Hire me!"
backEnd[5] = "Bring me onto your ship captain!"
backEnd[6] = "I'd love to sail the 7 seas with you!"
backEnd[7] = "I'm ready to work hard!"
backEnd[8] = "You could use a pirate like me!"
backEnd[9] = "You should take me on your ship!"

